export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const GET_URLS = 'GET_URLS'
export const ADD_URL = 'ADD_URL'
export const UPDATE_URL = 'UPDATE_URL'
export const DELETE_URL = 'DELETE_URL'
export const UPDATE_CHECKBOX = 'UPDATE_CHECKBOX'
export const TOGGLE_LOADING = 'TOGGLE_LOADING'